// coverage:ignore-file
import 'package:chatnest/app/pages/pages.dart';
import 'package:chatnest/app/pages/setting_screen/screens/chat/clear_chat_select_screen.dart';
import 'package:chatnest/app/screen_demo.dart';
import 'package:chatnest/app/widgets/pdf_view_widget.dart';
import 'package:chatnest/app/widgets/widgets.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
part 'app_routes.dart';

/// Contains the list of pages or routes taken across the whole application.
/// This will prevent us in using context for navigation. And also providing
/// the blocs required in the next named routes.
///
/// [pages] : will contain all the pages in the application as a route
/// and will be used in the material app.
/// Will be ignored for test since all are static values and would not change.
class AppPages {
  static var transitionDuration = const Duration(milliseconds: 300);

  static const initial = _Paths.splashScreen;
  static final pages = <GetPage>[
    GetPage<SplashScreen>(
      name: _Paths.splashScreen,
      transitionDuration: transitionDuration,
      page: SplashScreen.new,
      binding: SplashBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<EulaScreen>(
      name: _Paths.eulaScreen,
      transitionDuration: transitionDuration,
      page: EulaScreen.new,
      transition: Transition.fadeIn,
    ),
    GetPage<HideChatVerifyPinScreen>(
      name: _Paths.hideChatVerifyPinScreen,
      transitionDuration: transitionDuration,
      page: HideChatVerifyPinScreen.new,
      binding: HidechatBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<Logingscreen>(
      name: _Paths.logingScreen,
      transitionDuration: transitionDuration,
      page: Logingscreen.new,
      binding: LoginBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<RequestScreen>(
      name: _Paths.requestScreen,
      transitionDuration: transitionDuration,
      page: RequestScreen.new,
      binding: RequestBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<OtpScreen>(
      name: _Paths.otpScreen,
      transitionDuration: transitionDuration,
      page: OtpScreen.new,
      binding: LoginBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<HomeScreenScreen>(
      name: _Paths.homeScreen,
      transitionDuration: transitionDuration,
      page: HomeScreenScreen.new,
      binding: HomeScreenBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<ShareLocationScreen>(
      name: _Paths.shareLocationScreen,
      transitionDuration: transitionDuration,
      page: ShareLocationScreen.new,
      binding: ChatBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<CreateProfileScreen>(
      name: _Paths.createProfileScreen,
      transitionDuration: transitionDuration,
      page: CreateProfileScreen.new,
      binding: ProfileBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<ChangeBusinessHours>(
      name: _Paths.changeBusniessHours,
      transitionDuration: transitionDuration,
      page: ChangeBusinessHours.new,
      binding: ProfileBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<FindFriendScreen>(
      name: _Paths.findFriend,
      transitionDuration: transitionDuration,
      page: FindFriendScreen.new,
      binding: FindFriendBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<RequestHistoryScreen>(
      name: _Paths.findFriendrequesthistory,
      transitionDuration: transitionDuration,
      page: RequestHistoryScreen.new,
      binding: FindFriendBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<ShowFullScareenImage>(
      name: _Paths.showFullImageVideo,
      transitionDuration: transitionDuration,
      page: ShowFullScareenImage.new,
      binding: ProfileBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<PdfViewWidget>(
      name: _Paths.pdfViewWidgets,
      transitionDuration: transitionDuration,
      page: PdfViewWidget.new,
      binding: ProfileBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<CallInfoScreen>(
      name: _Paths.callInfoScreen,
      transitionDuration: transitionDuration,
      page: CallInfoScreen.new,
      binding: CallBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<ContactListScreen>(
      name: _Paths.contactListScreen,
      transitionDuration: transitionDuration,
      page: ContactListScreen.new,
      binding: CallBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<BroadCastListScreen>(
      name: _Paths.broadCastListScreen,
      transitionDuration: transitionDuration,
      page: BroadCastListScreen.new,
      binding: BroadCastBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<AddBroadCastScreen>(
      name: _Paths.addBordCastScreen,
      transitionDuration: transitionDuration,
      page: AddBroadCastScreen.new,
      binding: BroadCastBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<AddBroadcastTitle>(
      name: _Paths.addBordCastTitleScreen,
      transitionDuration: transitionDuration,
      page: AddBroadcastTitle.new,
      binding: BroadCastBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<BroadCastChatScreen>(
      name: _Paths.broadcastChatScreen,
      transitionDuration: transitionDuration,
      page: BroadCastChatScreen.new,
      binding: BroadCastBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<BookmarkScreen>(
      name: _Paths.bookmarkScreen,
      transitionDuration: transitionDuration,
      page: BookmarkScreen.new,
      binding: ChatBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<ProductScreen>(
      name: _Paths.productScreen,
      transitionDuration: transitionDuration,
      page: ProductScreen.new,
      binding: ProductBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<ProductDetailsScreen>(
      name: _Paths.productDetailsScreen,
      transitionDuration: transitionDuration,
      page: ProductDetailsScreen.new,
      binding: ProductBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<ShowAllProductScreen>(
      name: _Paths.showAllProductScreen,
      transitionDuration: transitionDuration,
      page: ShowAllProductScreen.new,
      binding: ProductBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<GroupCheatScreen>(
      name: _Paths.groupcheatScreen,
      transitionDuration: transitionDuration,
      page: GroupCheatScreen.new,
      binding: HidechatBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<ProductFilterScreen>(
      name: _Paths.productDetailsFilterScreen,
      transitionDuration: transitionDuration,
      page: ProductFilterScreen.new,
      binding: ProductBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<LocationScreen>(
      name: _Paths.locationScreen,
      transitionDuration: transitionDuration,
      page: LocationScreen.new,
      binding: ProfileBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<UserProfileScreen>(
      name: _Paths.userProfileScreen,
      transitionDuration: transitionDuration,
      page: UserProfileScreen.new,
      binding: ProfileBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<BusinessProductScreen>(
      name: _Paths.bussinessProductScreen,
      transitionDuration: transitionDuration,
      page: BusinessProductScreen.new,
      binding: ProductBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<AddBusinessProductScreen>(
      name: _Paths.addbusinessProductScreen,
      transitionDuration: transitionDuration,
      page: AddBusinessProductScreen.new,
      binding: ProductBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<BusinessProductDetailScreen>(
      name: _Paths.businessproductdetailScreen,
      transitionDuration: transitionDuration,
      page: BusinessProductDetailScreen.new,
      binding: ProductBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<LocationScreen>(
      name: _Paths.locationScreen,
      transitionDuration: transitionDuration,
      page: LocationScreen.new,
      binding: ProfileBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<PersonalProfileScreen>(
      name: _Paths.personalProfileScreen,
      transitionDuration: transitionDuration,
      page: PersonalProfileScreen.new,
      binding: ProfileBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<CreateBusinessProfileScreen>(
      name: _Paths.businessProfileScreen,
      transitionDuration: transitionDuration,
      page: () => CreateBusinessProfileScreen(key: UniqueKey()),
      binding: ProfileBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<SettingScreen>(
      name: _Paths.settingScreen,
      transitionDuration: transitionDuration,
      page: SettingScreen.new,
      binding: SettingBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<CreateGroupScreen>(
      name: _Paths.createGroupScreen,
      transitionDuration: transitionDuration,
      page: CreateGroupScreen.new,
      binding: GroupChatBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<CreateGroupTitleScreen>(
      name: _Paths.createGroupTitleScreen,
      transitionDuration: transitionDuration,
      page: CreateGroupTitleScreen.new,
      binding: GroupChatBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<CreateGroupTitleScreen>(
      name: _Paths.createGroupTitleScreen,
      transitionDuration: transitionDuration,
      page: CreateGroupTitleScreen.new,
      binding: GroupChatBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<GroupChatScreen>(
      name: _Paths.groupChatScreen,
      transitionDuration: transitionDuration,
      page: GroupChatScreen.new,
      binding: GroupChatBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<GroupProfileDetailsScreen>(
      name: _Paths.groupProfileDetailsScreen,
      transitionDuration: transitionDuration,
      page: GroupProfileDetailsScreen.new,
      binding: GroupChatBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<BroadCastProfileScreen>(
      name: _Paths.broadCastProfileScreen,
      transitionDuration: transitionDuration,
      page: BroadCastProfileScreen.new,
      binding: BroadCastBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<MeetingScreen>(
      name: _Paths.meetingScreen,
      transitionDuration: transitionDuration,
      page: MeetingScreen.new,
      binding: MeetingBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<HostMettingDetailScreen>(
      name: _Paths.hostMeetingDetailScreen,
      transitionDuration: transitionDuration,
      page: HostMettingDetailScreen.new,
      binding: MeetingBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<JoinMeetingDetailScreen>(
      name: _Paths.joinMeetingDetailScreen,
      transitionDuration: transitionDuration,
      page: JoinMeetingDetailScreen.new,
      binding: MeetingBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<AddMeetingScreen>(
      name: _Paths.addMeetingScreen,
      transitionDuration: transitionDuration,
      page: AddMeetingScreen.new,
      binding: MeetingBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<AddMembersScreen>(
      name: _Paths.addMeetingMemberScreen,
      transitionDuration: transitionDuration,
      page: AddMembersScreen.new,
      binding: MeetingBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<EditGroupDetailsScreen>(
      name: _Paths.editGroupDetailsScreen,
      transitionDuration: transitionDuration,
      page: EditGroupDetailsScreen.new,
      binding: GroupChatBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<ChatScreen>(
      name: _Paths.chatScreen,
      transitionDuration: transitionDuration,
      page: ChatScreen.new,
      binding: GroupChatBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<ChatUserProfilescreen>(
      name: _Paths.chatUserProfileScreen,
      transitionDuration: transitionDuration,
      page: ChatUserProfilescreen.new,
      binding: ChatBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<CreatePollScreen>(
      name: _Paths.createPollScreen,
      transitionDuration: transitionDuration,
      page: CreatePollScreen.new,
      binding: ChatBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<AudioScreen>(
      name: _Paths.audioScreen,
      transitionDuration: transitionDuration,
      page: AudioScreen.new,
      binding: ChatBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<ViewPollVoteScreen>(
      name: _Paths.viewPollVoteScreen,
      transitionDuration: transitionDuration,
      page: ViewPollVoteScreen.new,
      binding: ChatBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<ShareContactScreen>(
      name: _Paths.shareContactScreen,
      transitionDuration: transitionDuration,
      page: ShareContactScreen.new,
      binding: ChatBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<ViewAllSelectContactScreen>(
      name: _Paths.viewAllSelectContactScreen,
      transitionDuration: transitionDuration,
      page: ViewAllSelectContactScreen.new,
      binding: ChatBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<MultipalSendImageScreen>(
      name: _Paths.multipalSendImageScreen,
      transitionDuration: transitionDuration,
      page: MultipalSendImageScreen.new,
      binding: ChatBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<ViewAllContact>(
      name: _Paths.ViewAllContact,
      transitionDuration: transitionDuration,
      page: ViewAllContact.new,
      binding: ChatBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<ChatProductScreen>(
      name: _Paths.chatProductScreen,
      transitionDuration: transitionDuration,
      page: ChatProductScreen.new,
      binding: ChatBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<MessageInfoScreen>(
      name: _Paths.messageInfoScreen,
      transitionDuration: transitionDuration,
      page: MessageInfoScreen.new,
      binding: ChatBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<GroupMessageInfoScreen>(
      name: _Paths.groupMessageInfoScreen,
      transitionDuration: transitionDuration,
      page: GroupMessageInfoScreen.new,
      binding: ChatBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<ForwardMessageScreen>(
      name: _Paths.forwardMessageScreen,
      transitionDuration: transitionDuration,
      page: ForwardMessageScreen.new,
      binding: ChatBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<ViewAllImages>(
      name: _Paths.viewAllImages,
      transitionDuration: transitionDuration,
      page: ViewAllImages.new,
      binding: ChatBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<ForwardMessageGroupScreen>(
      name: _Paths.forwardMessageGroupScreen,
      transitionDuration: transitionDuration,
      page: ForwardMessageGroupScreen.new,
      binding: GroupChatBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<VideoCallScreen>(
      name: _Paths.videoCallScreen,
      transitionDuration: transitionDuration,
      page: () => VideoCallScreen(key: UniqueKey()),
      binding: VideoCallBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<AudioCallScreen>(
      name: _Paths.audioCallScreen,
      transitionDuration: transitionDuration,
      page: AudioCallScreen.new,
      binding: AudioCallBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<SharedMediascreen>(
      name: _Paths.sharedMediascreen,
      transitionDuration: transitionDuration,
      page: SharedMediascreen.new,
      binding: ChatBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<SingleFullScreenImageVideo>(
      name: _Paths.showFullScreenImageVideo,
      transitionDuration: transitionDuration,
      page: SingleFullScreenImageVideo.new,
      binding: ProfileBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<FavoriteMessageScreen>(
      name: _Paths.favoriteMessageScreen,
      transitionDuration: transitionDuration,
      page: FavoriteMessageScreen.new,
      binding: ChatBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<GroupFavoriteMessageScreen>(
      name: _Paths.groupFavoriteMessageScreen,
      transitionDuration: transitionDuration,
      page: GroupFavoriteMessageScreen.new,
      binding: GroupChatBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<BrodcastFavoriteListScreen>(
      name: _Paths.brodcastFavoriteListScreen,
      transitionDuration: transitionDuration,
      page: BrodcastFavoriteListScreen.new,
      binding: BroadCastBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<MeetingCallScreen>(
      name: _Paths.meetingCallScreen,
      transitionDuration: transitionDuration,
      page: MeetingCallScreen.new,
      binding: MeetingCallBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<LoginSubUserScreen>(
      name: _Paths.loginSubUserScreen,
      transitionDuration: transitionDuration,
      page: LoginSubUserScreen.new,
      binding: LoginBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<MyAccountScreen>(
      name: _Paths.myAccountScreen,
      transitionDuration: transitionDuration,
      page: MyAccountScreen.new,
      binding: SettingBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<ChangeNumberScreen>(
      name: _Paths.changeNumberScreen,
      transitionDuration: transitionDuration,
      page: ChangeNumberScreen.new,
      binding: SettingBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<CreateMultiUserScreen>(
      name: _Paths.createMultiUserScreen,
      transitionDuration: transitionDuration,
      page: CreateMultiUserScreen.new,
      binding: SettingBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<MultiUserScreen>(
      name: _Paths.multiUserScreen,
      transitionDuration: transitionDuration,
      page: MultiUserScreen.new,
      binding: SettingBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<AssignUserScreen>(
      name: _Paths.assignUserScreen,
      transitionDuration: transitionDuration,
      page: AssignUserScreen.new,
      binding: SettingBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<NotificationScreen>(
      name: _Paths.notificationScreen,
      transitionDuration: transitionDuration,
      page: NotificationScreen.new,
      binding: SettingBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<AllNotificationScreen>(
      name: _Paths.allNotificationScreen,
      transitionDuration: transitionDuration,
      page: AllNotificationScreen.new,
      binding: SettingBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<StorageScreen>(
      name: _Paths.storageScreen,
      transitionDuration: transitionDuration,
      page: StorageScreen.new,
      binding: SettingBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<PrivacySecurityScreen>(
      name: _Paths.privacySecurityScreen,
      transitionDuration: transitionDuration,
      page: PrivacySecurityScreen.new,
      binding: SettingBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<PrivacyPolicyScreen>(
      name: _Paths.privacyPolicyScreen,
      transitionDuration: transitionDuration,
      page: PrivacyPolicyScreen.new,
      binding: SettingBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<TermConditionScreen>(
      name: _Paths.termConditionScreen,
      transitionDuration: transitionDuration,
      page: TermConditionScreen.new,
      binding: SettingBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<HelpScreen>(
      name: _Paths.helpScreen,
      transitionDuration: transitionDuration,
      page: HelpScreen.new,
      binding: SettingBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<RecoveryEmailScreen>(
      name: _Paths.recoveryEmailScreen,
      transitionDuration: transitionDuration,
      page: RecoveryEmailScreen.new,
      binding: SettingBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<ChatSettingScreen>(
      name: _Paths.chatSettingScreen,
      transitionDuration: transitionDuration,
      page: ChatSettingScreen.new,
      binding: SettingBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<ChatWallpaperScreen>(
      name: _Paths.chatWallpaperScreen,
      transitionDuration: transitionDuration,
      page: ChatWallpaperScreen.new,
      binding: ChatBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<ChatWallpaperPreviewScreen>(
      name: _Paths.chatWallpaperPreviewScreen,
      transitionDuration: transitionDuration,
      page: ChatWallpaperPreviewScreen.new,
      binding: ChatBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<RingtoneScreen>(
      name: _Paths.ringtoneScreen,
      transitionDuration: transitionDuration,
      page: RingtoneScreen.new,
      binding: SettingBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<ForgotHideChatScreen>(
      name: _Paths.forgotHideChatScreen,
      transitionDuration: transitionDuration,
      page: ForgotHideChatScreen.new,
      binding: HidechatBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<ChangeHideChatScreen>(
      name: _Paths.changeHideChatScreen,
      transitionDuration: transitionDuration,
      page: ChangeHideChatScreen.new,
      binding: HidechatBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<CreatChatLockPinScreen>(
      name: _Paths.creatChatLockPinScreen,
      transitionDuration: transitionDuration,
      page: CreatChatLockPinScreen.new,
      binding: ChatBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<CreateHideChatPinScreen>(
      name: _Paths.createHideChatPinScreen,
      transitionDuration: transitionDuration,
      page: CreateHideChatPinScreen.new,
      binding: HidechatBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<HideChatScreen>(
      name: _Paths.hideChatScreen,
      transitionDuration: transitionDuration,
      page: HideChatScreen.new,
      binding: HidechatBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<ChatLockVerifyScreen>(
      name: _Paths.chatLockVerifyScreen,
      transitionDuration: transitionDuration,
      page: ChatLockVerifyScreen.new,
      binding: ChatBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<ChatLockScreen>(
      name: _Paths.chatLockScreen,
      transitionDuration: transitionDuration,
      page: ChatLockScreen.new,
      binding: ChatBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<ForgotLockChatScreen>(
      name: _Paths.forgotLockChatScreen,
      transitionDuration: transitionDuration,
      page: ForgotLockChatScreen.new,
      binding: ChatBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<ChangeLockChatScreen>(
      name: _Paths.changeLockChatScreen,
      transitionDuration: transitionDuration,
      page: ChangeLockChatScreen.new,
      binding: ChatBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<SubUserChangePasswordScreen>(
      name: _Paths.subUserChangePasswordScreen,
      transitionDuration: transitionDuration,
      page: SubUserChangePasswordScreen.new,
      binding: SettingBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<ChangeLockForgotPinScreen>(
      name: _Paths.changeLockForgotPinScreen,
      transitionDuration: transitionDuration,
      page: ChangeLockForgotPinScreen.new,
      binding: ChatBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<ChangeHideForgotPinScreen>(
      name: _Paths.changeHideForgotPinScreen,
      transitionDuration: transitionDuration,
      page: ChangeHideForgotPinScreen.new,
      binding: HidechatBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<ArchiveScreen>(
      name: _Paths.archiveScreen,
      transitionDuration: transitionDuration,
      page: ArchiveScreen.new,
      binding: ChatBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<ArchiveGroupScreen>(
      name: _Paths.archiveGroupScreen,
      transitionDuration: transitionDuration,
      page: ArchiveGroupScreen.new,
      binding: GroupChatBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<NotificationListScreen>(
      name: _Paths.notificationListScreen,
      transitionDuration: transitionDuration,
      page: NotificationListScreen.new,
      binding: ChatBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<ChatUserBookmarkScreen>(
      name: _Paths.chatUserBookmarkScreen,
      transitionDuration: transitionDuration,
      page: ChatUserBookmarkScreen.new,
      binding: ChatBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<ShareUserContactScreen>(
      name: _Paths.shareUserContactScreen,
      transitionDuration: transitionDuration,
      page: ShareUserContactScreen.new,
      binding: ChatBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<ReportUserScreen>(
      name: _Paths.reportUserScreen,
      transitionDuration: transitionDuration,
      page: ReportUserScreen.new,
      binding: ChatBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<ReportGroupScreen>(
      name: _Paths.reportGroupScreen,
      transitionDuration: transitionDuration,
      page: ReportGroupScreen.new,
      binding: GroupChatBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<ReportUserGroupListScreen>(
      name: _Paths.reportUserGroupListScreen,
      transitionDuration: transitionDuration,
      page: ReportUserGroupListScreen.new,
      binding: SettingBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<GetOneReportScreen>(
      name: _Paths.getOneReportScreen,
      transitionDuration: transitionDuration,
      page: GetOneReportScreen.new,
      binding: SettingBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<ChatProductDetailsScreen>(
      name: _Paths.chatProductDetailsScreen,
      transitionDuration: transitionDuration,
      page: ChatProductDetailsScreen.new,
      binding: ChatBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<ScreenDemo>(
      name: _Paths.screenDemo,
      transitionDuration: transitionDuration,
      page: ScreenDemo.new,
      binding: HomeScreenBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<ClearChatSelectScreen>(
      name: _Paths.clearChatSelectScreen,
      transitionDuration: transitionDuration,
      page: ClearChatSelectScreen.new,
      binding: SettingBinding(),
      transition: Transition.fadeIn,
    ),
  ];
}
